# Generated by Django 4.0.5 on 2022-06-29 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bands", "0001_initial"),
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "band",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="bands.band",
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        related_name="albums", to="shared.genre"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "genre",
                    models.ManyToManyField(
                        related_name="songs", to="shared.genre"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=3, max_digits=6),
                ),
                ("is_single", models.BooleanField()),
            ],
        ),
    ]
